image: Visual Studio 2017 RC

version: 0.1.{build}

configuration: Release

before_build:

- set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
- dotnet restore

build:
  verbosity: minimal
  
after_build:
- dotnet test
  
test: off